version: '3'

services:
  nginx:
    image: nginx
    restart: "always"
    networks:
      - backend-network
      - external-network
    ports:
      - 8080:80
    volumes:
      - "./docker/nginx/notificator.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/srv/:rw"
    depends_on: # load after php-fpm
      - php-fpm

  php-fpm:
    build: ./docker/php
    entrypoint: entrypoint.sh default
    command: docker-php-entrypoint php-fpm
    networks:
      - backend-network
      - external-network
    env_file:
      - ./app/.env
    expose:
      - 9000
    volumes:
      - "./app:/srv/:rw"
    depends_on:
      - redis
      - db

  horizon:
    build: ./docker/php
    entrypoint: entrypoint.sh horizon
    command: docker-php-entrypoint php-fpm
    networks:
      - backend-network
      - external-network
    expose:
      - 9000
    volumes:
      - "./app:/srv/:rw"
      - "./docker/php:/tmp"

  redis:
    build: ./docker/redis
    networks:
      - backend-network
    environment:
      REDIS_PASSWORD: example
    entrypoint: sh /app/entrypoint.sh
    expose:
      - 6379

  db:
    image: postgres
    networks:
      - backend-network
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
      POSTGRES_DB: notificator
    expose:
      - 5432
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    networks:
      - external-network
      - backend-network
    restart: always
    ports:
      - 8081:8080

networks:
  backend-network:
    internal: true
  external-network:
    driver: "bridge"